services:
  ros2:
    build: .
    container_name: nmpc_controller
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - PYTHONUNBUFFERED=1  
    privileged: true
    volumes:
      - ./ros2_ws:/home/user/ros2_ws
    tty: true
    stdin_open: true
    working_dir: /home/user/ros2_ws
    command: /bin/bash